require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RawChannelsController do

  # This should return the minimal set of attributes required to create a valid
  # RawChannel. As you add validations to RawChannel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RawChannelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all raw_channels as @raw_channels" do
      raw_channel = RawChannel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:raw_channels).should eq([raw_channel])
    end
  end

  describe "GET show" do
    it "assigns the requested raw_channel as @raw_channel" do
      raw_channel = RawChannel.create! valid_attributes
      get :show, {:id => raw_channel.to_param}, valid_session
      assigns(:raw_channel).should eq(raw_channel)
    end
  end

  describe "GET new" do
    it "assigns a new raw_channel as @raw_channel" do
      get :new, {}, valid_session
      assigns(:raw_channel).should be_a_new(RawChannel)
    end
  end

  describe "GET edit" do
    it "assigns the requested raw_channel as @raw_channel" do
      raw_channel = RawChannel.create! valid_attributes
      get :edit, {:id => raw_channel.to_param}, valid_session
      assigns(:raw_channel).should eq(raw_channel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RawChannel" do
        expect {
          post :create, {:raw_channel => valid_attributes}, valid_session
        }.to change(RawChannel, :count).by(1)
      end

      it "assigns a newly created raw_channel as @raw_channel" do
        post :create, {:raw_channel => valid_attributes}, valid_session
        assigns(:raw_channel).should be_a(RawChannel)
        assigns(:raw_channel).should be_persisted
      end

      it "redirects to the created raw_channel" do
        post :create, {:raw_channel => valid_attributes}, valid_session
        response.should redirect_to(RawChannel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raw_channel as @raw_channel" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawChannel.any_instance.stub(:save).and_return(false)
        post :create, {:raw_channel => {}}, valid_session
        assigns(:raw_channel).should be_a_new(RawChannel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawChannel.any_instance.stub(:save).and_return(false)
        post :create, {:raw_channel => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raw_channel" do
        raw_channel = RawChannel.create! valid_attributes
        # Assuming there are no other raw_channels in the database, this
        # specifies that the RawChannel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RawChannel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => raw_channel.to_param, :raw_channel => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested raw_channel as @raw_channel" do
        raw_channel = RawChannel.create! valid_attributes
        put :update, {:id => raw_channel.to_param, :raw_channel => valid_attributes}, valid_session
        assigns(:raw_channel).should eq(raw_channel)
      end

      it "redirects to the raw_channel" do
        raw_channel = RawChannel.create! valid_attributes
        put :update, {:id => raw_channel.to_param, :raw_channel => valid_attributes}, valid_session
        response.should redirect_to(raw_channel)
      end
    end

    describe "with invalid params" do
      it "assigns the raw_channel as @raw_channel" do
        raw_channel = RawChannel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawChannel.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_channel.to_param, :raw_channel => {}}, valid_session
        assigns(:raw_channel).should eq(raw_channel)
      end

      it "re-renders the 'edit' template" do
        raw_channel = RawChannel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawChannel.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_channel.to_param, :raw_channel => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raw_channel" do
      raw_channel = RawChannel.create! valid_attributes
      expect {
        delete :destroy, {:id => raw_channel.to_param}, valid_session
      }.to change(RawChannel, :count).by(-1)
    end

    it "redirects to the raw_channels list" do
      raw_channel = RawChannel.create! valid_attributes
      delete :destroy, {:id => raw_channel.to_param}, valid_session
      response.should redirect_to(raw_channels_url)
    end
  end

end
