require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RawProgramsController do

  # This should return the minimal set of attributes required to create a valid
  # RawProgram. As you add validations to RawProgram, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RawProgramsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all raw_programs as @raw_programs" do
      raw_program = RawProgram.create! valid_attributes
      get :index, {}, valid_session
      assigns(:raw_programs).should eq([raw_program])
    end
  end

  describe "GET show" do
    it "assigns the requested raw_program as @raw_program" do
      raw_program = RawProgram.create! valid_attributes
      get :show, {:id => raw_program.to_param}, valid_session
      assigns(:raw_program).should eq(raw_program)
    end
  end

  describe "GET new" do
    it "assigns a new raw_program as @raw_program" do
      get :new, {}, valid_session
      assigns(:raw_program).should be_a_new(RawProgram)
    end
  end

  describe "GET edit" do
    it "assigns the requested raw_program as @raw_program" do
      raw_program = RawProgram.create! valid_attributes
      get :edit, {:id => raw_program.to_param}, valid_session
      assigns(:raw_program).should eq(raw_program)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RawProgram" do
        expect {
          post :create, {:raw_program => valid_attributes}, valid_session
        }.to change(RawProgram, :count).by(1)
      end

      it "assigns a newly created raw_program as @raw_program" do
        post :create, {:raw_program => valid_attributes}, valid_session
        assigns(:raw_program).should be_a(RawProgram)
        assigns(:raw_program).should be_persisted
      end

      it "redirects to the created raw_program" do
        post :create, {:raw_program => valid_attributes}, valid_session
        response.should redirect_to(RawProgram.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raw_program as @raw_program" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawProgram.any_instance.stub(:save).and_return(false)
        post :create, {:raw_program => {}}, valid_session
        assigns(:raw_program).should be_a_new(RawProgram)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawProgram.any_instance.stub(:save).and_return(false)
        post :create, {:raw_program => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raw_program" do
        raw_program = RawProgram.create! valid_attributes
        # Assuming there are no other raw_programs in the database, this
        # specifies that the RawProgram created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RawProgram.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => raw_program.to_param, :raw_program => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested raw_program as @raw_program" do
        raw_program = RawProgram.create! valid_attributes
        put :update, {:id => raw_program.to_param, :raw_program => valid_attributes}, valid_session
        assigns(:raw_program).should eq(raw_program)
      end

      it "redirects to the raw_program" do
        raw_program = RawProgram.create! valid_attributes
        put :update, {:id => raw_program.to_param, :raw_program => valid_attributes}, valid_session
        response.should redirect_to(raw_program)
      end
    end

    describe "with invalid params" do
      it "assigns the raw_program as @raw_program" do
        raw_program = RawProgram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawProgram.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_program.to_param, :raw_program => {}}, valid_session
        assigns(:raw_program).should eq(raw_program)
      end

      it "re-renders the 'edit' template" do
        raw_program = RawProgram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawProgram.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_program.to_param, :raw_program => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raw_program" do
      raw_program = RawProgram.create! valid_attributes
      expect {
        delete :destroy, {:id => raw_program.to_param}, valid_session
      }.to change(RawProgram, :count).by(-1)
    end

    it "redirects to the raw_programs list" do
      raw_program = RawProgram.create! valid_attributes
      delete :destroy, {:id => raw_program.to_param}, valid_session
      response.should redirect_to(raw_programs_url)
    end
  end

end
